//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamousBookstore
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderID { get; set; }
        public string UserName { get; set; }
        public int BookID { get; set; }
        public int Quantity { get; set; }
        public decimal finalprice { get; set; }
        public decimal Totalprice { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
